name: seed-app

services:
  postgres:
    image: postgres:16-alpine
    container_name: seed-postgres
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    container_name: seed-api
    build:
      context: ../backend
      dockerfile: src/Seed.Api/Dockerfile
    ports:
      - "5035:8080"
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - JwtSettings__Secret=${JwtSettings__Secret}
      - AllowedHosts=${AllowedHosts}
    depends_on:
      - postgres

  web:
    container_name: seed-web
    build:
      context: ../frontend/web
      dockerfile: Dockerfile
      args:
        ANGULAR_BUILD_CONFIGURATION: docker
    ports:
      - "4200:80"
    depends_on:
      - api

volumes:
  postgres_data:
